// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "apps-management": apps Resource Client
//
// Command:
// $ goagen
// --design=github.com/JormungandrK/microservice-apps-management/design
// --out=$(GOPATH)/src/github.com/JormungandrK/microservice-apps-management
// --version=v1.2.0-dirty

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// GetAppsPath computes a request path to the get action of apps.
func GetAppsPath(appID string) string {
	param0 := appID

	return fmt.Sprintf("/apps/%s", param0)
}

// Get app by id
func (c *Client) GetApps(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewGetAppsRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewGetAppsRequest create the request corresponding to the get action endpoint of the apps resource.
func (c *Client) NewGetAppsRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
