// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "apps-management": Application Contexts
//
// Command:
// $ goagen
// --design=github.com/JormungandrK/microservice-apps-management/design
// --out=$(GOPATH)/src/github.com/JormungandrK/microservice-apps-management
// --version=v1.2.0-dirty

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// GetAppsContext provides the apps get action context.
type GetAppsContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	AppID string
}

// NewGetAppsContext parses the incoming request URL and body, performs validations and creates the
// context used by the apps controller get action.
func NewGetAppsContext(ctx context.Context, r *http.Request, service *goa.Service) (*GetAppsContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := GetAppsContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramAppID := req.Params["appId"]
	if len(paramAppID) > 0 {
		rawAppID := paramAppID[0]
		rctx.AppID = rawAppID
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *GetAppsContext) OK(r *Apps) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.apps+json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// BadRequest sends a HTTP response with status code 400.
func (ctx *GetAppsContext) BadRequest(r error) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	return ctx.ResponseData.Service.Send(ctx.Context, 400, r)
}

// NotFound sends a HTTP response with status code 404.
func (ctx *GetAppsContext) NotFound(r error) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	return ctx.ResponseData.Service.Send(ctx.Context, 404, r)
}

// InternalServerError sends a HTTP response with status code 500.
func (ctx *GetAppsContext) InternalServerError(r error) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	return ctx.ResponseData.Service.Send(ctx.Context, 500, r)
}
