// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "apps-management": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/Microkubes/microservice-apps-management/design
// --out=$(GOPATH)/src/github.com/Microkubes/microservice-apps-management
// --version=v1.3.1

package app
