package db

import (
	"testing"
)

func TestHexToObjectID(t *testing.T) {
	hexObjID := "599e8545da144128eb510159"
	fakeObjID := "qwessdf"

	bsonObjID, _ := hexToObjectID(hexObjID)
	if bsonObjID == "" {
		t.Fatal("Expected to have bson object ID")
	}

	_, err := hexToObjectID(fakeObjID)
	if err == nil {
		t.Errorf("Expected to get error: invalid metadata ID, got: %v", err)
	}
}

func TestGenerateRandomBytes(t *testing.T) {
	bytes, err := GenerateRandomBytes(42)

	if err != nil {
		t.Fatal(err)
	}

	if len(bytes) != 42 {
		t.Fatal("Invalid generated bytes")
	}
}

func TestGenerateRandomString(t *testing.T) {
	str, err := GenerateRandomString(42)

	if err != nil {
		t.Fatal(err)
	}

	if str == "" {
		t.Fatal("Nil string.")
	}
}

func TestValidateDomain(t *testing.T) {
	err := validateDomain("example.com")

	if err != nil {
		t.Fatal(err)
	}

	err = validateDomain("example")
	if err == nil {
		t.Fatal("Nil error from domain validation")
	}
}
